name: Grill CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  grill:
    runs-on: ubuntu-latest
    container:
      image: frotty/wurstscript

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install project dependencies
        run: grill install

      - name: Typecheck
        run: grill typecheck

      - name: Test
        run: grill test
